### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hughperkins** [ChenglongChen/pytorch-madrl#1]
Hi,

What is the license?

Hugh

**Comment by hughperkins** [comment]
(eg `MIT` is fairly standard, github has some functions to make adding a license fairly straightforward, though I confess to not having tested them: https://help.github.com/articles/adding-a-license-to-a-repository/ )

**Comment by ChenglongChen** [comment]
MIT license is added. Thanks for the info.

**Comment by hughperkins** [comment]
Awesome, thanks! :)
